### ISSUE TITLE
Failed to upload playbook to Cloud Shell: StorageError: Forbidden

### ISSUE THREAD

**Issue by hadr10** [VSChina/vscode-ansible#133]
## Environment
- Extension version: 
- OS Type: Windows

## Summary
when I run in vscode: Ansbile: run ansible playbook in cloud shell I get this error message:
Connecting to Cloud Shell.............
Failed to upload playbook to Cloud Shell: StorageError: Forbidden

## Reproduce steps
when I run in vscode: Ansbile: run ansible playbook in cloud shell I get this error message:
Connecting to Cloud Shell.............
Failed to upload playbook to Cloud Shell: StorageError: Forbidden

## Expected Results
That I connect to cloud shell successfully

## Actual Results
Connecting to Cloud Shell.............
Failed to upload playbook to Cloud Shell: StorageError: Forbidden

**Comment by yungezz** [comment]
@hadr10  thanks for reporting the issue. could you pls try to upload something to your cloud shell through portal?

**Comment by yungezz** [comment]
@hadr10 v0.3.0 released, with a change to create CloudShell with sdk api. could  you pls retry it and let us know if still the error?

**Comment by yungezz** [comment]
Finally I reproduced the error  on  one of my laptop. Debugging found that ansible extension got correct acocunt key and account name,  but call into Azure Storage service got a 403.  The issue isn't reproducable with my account on any other machine. I did a search seems it's caused by client machines' time  is out sync of services. It's environment related. I've created an [issue](https://github.com/Azure/azure-storage-node/issues/490) in azure-storage repo to get help.

Meanwhile, @hadr10  could you pls try it from another machine, without any hyper-v or dual boot system, to see if the error persistent?

**Comment by hadr10** [comment]
@yungezz  thank you

**Comment by yungezz** [comment]
fixed in release 0.4.0. Pls have a try and let us know if any other issue.
