### ISSUE TITLE
ec2 module doesn't provide snippet

### ISSUE THREAD

**Issue by christonog** [VSChina/vscode-ansible#153]
## Environment
- Extension version: 0.3.1
- OS Type: MacOS

## Summary

When attempting to autocomplete on the ec2 module https://docs.ansible.com/ansible/2.6/modules/ec2_module.html
 I don't get the option to get a snippet

## Reproduce steps
in VSCode with the add-on installed, try creating a playbook with the `ec2` module.

## Expected Results

I should get a snippet option for `- ec2: `

## Actual Results
Snippet options for other `ec2_*` modules, but not the actual `ec2` module.

<img width="765" alt="screen shot 2018-08-12 at 12 36 01 pm" src="https://user-images.githubusercontent.com/29683/44004201-b0e231cc-9e2c-11e8-9849-cb950d943cb4.png">

**Comment by christonog** [comment]
Actually, no snippets are found for `ec2_ami` as well

**Comment by yungezz** [comment]
thanks for reporting the issue, we're looking at it now.

**Comment by yungezz** [comment]
@christonog  Just checked out snippet file, ec2 is still, and I tested windows and mac, both could show ec2_snippet . it's not there in your list because  `ec2_snippet` is at end of suggested list sorted  by `ec2`, you need type more word to make it showed upper such as `ec2_s`,  or scroll down to suggested list, then you'll see `ec2_snippet`.
