### ISSUE TITLE
Blockinfile complains about "dest" property, which has been renamed to "path"

### ISSUE THREAD

**Issue by Bak3y** [VSChina/vscode-ansible#198]
## Environment
- Extension version: 0.5.1
- OS Type: MacOS

## Summary
One of my playbooks is using blockinfile with the "path" property defined for the file I'm modifying.
VS Code complains of the missing property "dest" for blockinfile.  According to the documentation at https://docs.ansible.com/ansible/latest/modules/blockinfile_module.html, "dest" has been renamed to "path" as of Ansible 2.3.

## Reproduce steps
Install VSCode, install Ansible extension, create a playbook with blockinfile module.  Observe the complaints for blockinfile.

## Expected Results
Blockinfile check looks for the new "path" property as well as "dest."

## Actual Results
Blockinfile only looks for "dest," ignoring the (correct) "path" property.

**Comment by yungezz** [comment]
@Bak3y  thanks for reporting the issue.  when "VS Code complains of the missing property "dest" for blockinfile. ", it's from which operation? editing playbook or running playbook? If running playbook, which environment you'rer used?

**Comment by yungezz** [comment]
@Bak3y  just check that code snippet for `blockinfile` has `path` argument no `dest`, which is correct. I suspect your error is from running playbook. Then root cause is depends on where the playbook is running:
- if on docker, pls check ansible version in your docker container
- if on cloud shell, pls share our error because cloud shell ansible version is latest 2.7.0 already.
- if on remote host, pls check ansible version on your remote host
- if on local,  also pls check ansible version.

**Comment by yungezz** [comment]
this extension doesn't check module arguments correctness, but only yaml syntax validation. Could you pls share some screencut of the error to help investigating where the error from? Thanks.

**Comment by Bak3y** [comment]
Upon reopening VSCode and going back to this playbook, the "path" property is no longer flagged as incorrect.
